# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='code',
            field=models.CharField(default='X', max_length=1),
            preserve_default=False,
        ),
    ]
