# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0002_frame_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionframe',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
