# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0006_hivebox_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HiveBox',
            new_name='Box',
        ),
        migrations.RenameModel(
            old_name='Hive',
            new_name='Stand',
        ),
    ]
