# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0007_auto_20170418_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1)),
                ('order', models.PositiveSmallIntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hives.Box')),
                ('frame', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.Frame')),
            ],
        ),
    ]
