# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0009_auto_20170418_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='order',
        ),
    ]
