# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0010_remove_frame_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
