# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0011_box_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxposition',
            name='frame',
        ),
        migrations.AddField(
            model_name='inspectionframe',
            name='boxpos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.BoxPosition'),
        ),
        migrations.AlterField(
            model_name='inspectionframe',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.Frame'),
        ),
        migrations.AlterField(
            model_name='inspectionframe',
            name='img_back',
            field=filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_backs', to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='inspectionframe',
            name='img_front',
            field=filer.fields.image.FilerImageField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_fronts', to='filer.Image'),
        ),
    ]
