# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0013_auto_20170418_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='box',
        ),
    ]
