# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0014_remove_frame_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionframe',
            name='boxpos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hives.BoxPosition'),
        ),
    ]
