# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 14:09
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0015_auto_20170418_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionframe',
            name='img_back',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_backs', to='filer.Image'),
        ),
        migrations.AlterField(
            model_name='inspectionframe',
            name='img_front',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frame_fronts', to='filer.Image'),
        ),
    ]
