# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0016_auto_20170418_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionframe',
            options={'get_latest_by': 'inspection__timestamp'},
        ),
        migrations.AddField(
            model_name='frame',
            name='current_boxpos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.BoxPosition'),
        ),
    ]
