# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0017_auto_20170418_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.CharField(choices=[('W', "White ('1 or '6)"), ('Y', "Yellow ('2 or '7)"), ('R', "Red ('3 or '8)"), ('G', "Green ('4 or '9)"), ('B', "Blue ('5 or '0)")], max_length=1)),
                ('born', models.DateField()),
                ('stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.Stand')),
            ],
        ),
    ]
