# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0018_queen'),
    ]

    operations = [
        migrations.AddField(
            model_name='queen',
            name='breeder',
            field=models.CharField(default='Nobody', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='queen',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
