# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0019_auto_20170418_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queen',
            name='stand',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.Stand'),
        ),
    ]
