# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-18 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0020_auto_20170418_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='queen',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.Queen'),
        ),
    ]
