# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-04-20 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0021_queen_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionframe',
            name='brood',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='inspectionframe',
            name='new_boxpos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manipulations', to='hives.BoxPosition'),
        ),
        migrations.AddField(
            model_name='inspectionframe',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
