# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0022_auto_20170420_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hives.Box')),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hives.Stand')),
            ],
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
