# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 16:56
from __future__ import unicode_literals

from django.db import migrations

def make_boxhist_stubs(apps, editor):
    BoxHistory = apps.get_model("hives", "BoxHistory")
    Box = apps.get_model("hives", "Box")

    for box in Box.objects.all():
        bh = BoxHistory(box_id=box.id, stand_id=box.stand.id, order=box.order)
        bh.save()

class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0023_auto_20170502_1656'),
    ]

    operations = [
        migrations.RunPython(make_boxhist_stubs),
    ]
