# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0024_auto_20170502_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxhistory',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 2, 17, 32, 4, 590570, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
