# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0025_boxhistory_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='order',
            new_name='current_order',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='stand',
            new_name='current_stand',
        ),
    ]
