# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0026_auto_20170502_1733'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxHistory',
            new_name='InspectionBox',
        ),
        migrations.AlterModelOptions(
            name='inspectionbox',
            options={'get_latest_by': 'timestamp'},
        ),
    ]
