# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0027_auto_20170502_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionbox',
            name='inspection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='hives.Inspection'),
            preserve_default=False,
        ),
    ]
