# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0028_inspectionbox_inspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionbox',
            name='timestamp',
        ),
    ]
