# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-05-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0029_remove_inspectionbox_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FramePack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_type', models.CharField(choices=[('D', 'Deep'), ('S', 'Shallow')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='frame',
            name='code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='frame',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hives.FramePack'),
        ),
    ]
